

# POST /signup - Create a new user
POST http://localhost:8080/signup
Content-Type: application/json

{
    "password": "testpassword",
    "email": "testemail@mail.com"
}

###

# POST /login - Login with the created user
POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "testuser",
    "password": "testpassword"
}

###
 

# POST /logout - Logout (no request body needed)
DELETE http://localhost:8080/logout
Authorization: Bearer <token_from_login_response>


###

POST http://localhost:8080/tokens
Content-Type: application/json

{
    "token": "<Insert refreshToken>"
}

###

POST http://localhost:8080/database

###
